# Generated by Django 2.1.5 on 2019-03-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sperimentazione',
            old_name='lista_preferita',
            new_name='lista_preferita_interesse',
        ),
        migrations.AddField(
            model_name='sperimentazione',
            name='lista_preferita_personalita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sperimentazione',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
