# Generated by Django 2.1.5 on 2019-02-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sperimentazione',
            old_name='userId',
            new_name='user',
        ),
    ]
