# Generated by Django 2.1.5 on 2019-02-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sperimentazione',
            options={'managed': True},
        ),
    ]
